//! Contains setup code, including applying forcefield data to our specific
//! atoms.

// Notes to square away the 3 "atom name" / "Amber atom type" / "force field type" keys.
// This guide shows Type 1. https://emleddin.github.io/comp-chem-website/AMBERguide-AMBER-atom-types.html,
//
// Update: "Type 1" = "type_in_res" in our code now. "Type 2" = "ff_type" for AAs, and "Type 3" = "ff_type" for small mols.
//
// Type 1 Examples: "CA", "HA", "CZ", "HB3", "HH22", HZ2", "N", "H", "HG3", "O", "CD", "C", "HG23", "CG", "CB", "CG1", "HE2", "HB3",
// Type 1 Sources: `amino19.lib`, col 0. mmCIF atom coordinate files.
//
// Type 2 Examples:  "HC", "C8", "HC", "H"(both), "XC", "N"(both), "H"(both), "H1", "CT", "OH", "HO", "2C",
// Type 2 Sources: `amino19.lib` (AA/protein partial charges), col 1. `frcmod.ff19SB`. (AA/protein params)
//
// Small Mol/lig:
// Type 3 Examples: "oh", "h1", "ca", "o", "os", "c6", "n3", "c3"
// Type 3 Sources: `.mol2` generated by Amber. (Small mol coordinates and partial charges) `gaff2.dat` (Small molg params)
//
// MOl2 for ligands also have "C10", "O7" etc, which is ambiguous here, and not required, as their params
// use Type 3, which is present. It's clear what to do for ligand
//
// Best guess: Type 1 identifies labels within the residue only. Type 2 (AA) and Type 3 (small mol) are the FF types.

use std::{collections::HashSet, fmt};

#[cfg(feature = "encode")]
use bincode::{Decode, Encode};
use bio_files::{
    gromacs::mdp::{ConstraintAlgorithm, Constraints},
    md_params::ForceFieldParams,
};

use crate::MdState;
use crate::{ComputationDevice, AtomDynamics, ForceFieldParamsIndexed, LjTables, NeighborsNb, insert_ion, remove_waters, CHARGE_UNIT_SCALER};
use na_seq::Element;

/// Add items from one parameter set to the other. If there are duplicates, the second set's overrides
/// the baseline.
pub fn merge_params(baseline: &ForceFieldParams, add_this: &ForceFieldParams) -> ForceFieldParams {
    let mut merged = baseline.clone();

    merged.mass.extend(add_this.mass.clone());
    merged.lennard_jones.extend(add_this.lennard_jones.clone());

    merged.bond.extend(add_this.bond.clone());
    merged.angle.extend(add_this.angle.clone());
    merged.dihedral.extend(add_this.dihedral.clone());
    merged.improper.extend(add_this.improper.clone());

    merged
}

/// We use this variant in the configuration API. Deferrs to `HydrogenConstraintInner` for holding
/// constraints.
#[cfg_attr(feature = "encode", derive(Encode, Decode))]
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum HydrogenConstraint {
    /// A linear constraint solver. Similar to GROMACS' LINCS. This is slightly faster,
    /// and slightly more stable than SHAKE.
    Linear {
        order: u8,
        iter: u8,
    },
    Shake {
        shake_tolerance: f32,
    },
    /// Uses Shake and Rattle to fix the hydrogen positions. This allows for a larger timestep,
    /// e.g. 2fs instead of 1fs.
    /// Uses the same bonded parameters as elsewhere: A spring model
    Flexible,
}

impl Default for HydrogenConstraint {
    fn default() -> Self {
        // HydrogenConstraint::Shake {
        //     shake_tolerance: SHAKE_TOL_DEFAULT,
        // }
        // GROMACS defaults here.
        HydrogenConstraint::Linear { order: 4, iter: 1 }
    }
}

impl HydrogenConstraint {
    pub fn to_gromacs(&self) -> Constraints {
        match self {
            Self::Linear { order, iter } => Constraints::HBonds(ConstraintAlgorithm::Lincs {
                order: *order,
                iter: *iter,
            }),
            Self::Shake {
                shake_tolerance: tolerance,
            } => Constraints::HBonds(ConstraintAlgorithm::Shake { tol: *tolerance }),
            Self::Flexible => Constraints::None,
        }
    }
}

impl fmt::Display for HydrogenConstraint {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            HydrogenConstraint::Linear { .. } => {
                write!(f, "Constrained (LINCS)")
            }
            HydrogenConstraint::Shake { shake_tolerance: _ } => {
                write!(f, "Constrained (SHAKE)")
            }
            HydrogenConstraint::Flexible => write!(f, "Flexible"),
        }
    }
}

impl MdState {
    /// We use this to set up optimizations defined in the Amber reference manual. `excluded` deals
    /// with sections were we skip coulomb and Vdw interactions for atoms separated by 1 or 2 bonds. `scaled14` applies a force
    /// scaler for these interactions, when separated by 3 bonds.
    pub(crate) fn setup_nonbonded_exclusion_scale_flags(&mut self) {
        // Helper to store pairs in canonical (low,high) order
        let push = |set: &mut HashSet<(usize, usize)>, i: usize, j: usize| {
            if i < j {
                set.insert((i, j));
            } else {
                set.insert((j, i));
            }
        };

        // 1-2
        for indices in &self.force_field_params.bonds_topology {
            push(&mut self.pairs_excluded_12_13, indices.0, indices.1);
        }

        // 1-3
        for indices in self.force_field_params.angle.keys() {
            push(&mut self.pairs_excluded_12_13, indices.0, indices.2);
        }

        // 1-4. We do not count improper dihedrals here.
        for indices in self.force_field_params.dihedral.keys() {
            push(&mut self.pairs_14_scaled, indices.0, indices.3);
        }

        // Make sure no 1-4 pair is also in the excluded set
        for p in &self.pairs_14_scaled {
            self.pairs_excluded_12_13.remove(p);
        }
    }

    /// Reuses the solvent box, water, and ions of this state but replaces the solute atoms
    /// with the mutant solute atoms, rebuilding the force-field parameters and neighbor lists.
    pub fn build_mutant_by_solvent_reuse(
        &self,
        dev: &ComputationDevice,
        new_solute_atoms: Vec<AtomDynamics>,
        new_solute_adjacency: Vec<Vec<usize>>,
        new_ff_params: ForceFieldParamsIndexed,
    ) -> Self {
        let n_new_solute = new_solute_atoms.len();
        
        // 1. Combine new solute atoms with parent ions
        let parent_solute_count = self.solute_atom_count;
        let mut combined_atoms = new_solute_atoms;
        let mut parent_ions = self.atoms[parent_solute_count..].to_vec();
        
        combined_atoms.append(&mut parent_ions);

        // 2. Clone water molecules, but prune any water molecule that clashes with the new mutant solute!
        let mut water = Vec::new();
        let cutoff_clash_sq = 2.2 * 2.2; // 2.2 Å cutoff for steric clashes
        let mut pruned_count = 0;
        
        for w in &self.water {
            let mut clash = false;
            let o_pos = w.o.posit;
            for a in &combined_atoms[..n_new_solute] { // only check against the new solute atoms
                let diff = self.cell.min_image(o_pos - a.posit);
                if diff.magnitude_squared() < cutoff_clash_sq {
                    clash = true;
                    break;
                }
            }
            if clash {
                pruned_count += 1;
            } else {
                water.push(w.clone());
            }
        }
        
        if pruned_count > 0 {
            eprintln!(
                "[solvent_reuse] Pruned {} clashing water molecule(s) near mutated residues.",
                pruned_count
            );
        }

        // 3. Build combined mass_accel_factor
        let mut mass_accel_factor = Vec::with_capacity(combined_atoms.len());
        for a in &combined_atoms {
            mass_accel_factor.push(418.4 / a.mass);
        }

        // 4. Create new MdState
        let mut new_state = Self {
            cfg: self.cfg.clone(),
            atoms: combined_atoms,
            adjacency_list: new_solute_adjacency,
            water,
            cell: self.cell.clone(),
            force_field_params: new_ff_params,
            mass_accel_factor,
            solute_atom_count: n_new_solute,
            mol_start_indices: self.mol_start_indices.clone(),
            ..Default::default()
        };

        // Rebuild mol_start_indices
        let diff = n_new_solute as isize - parent_solute_count as isize;
        let mut new_mol_start_indices = Vec::new();
        if !self.mol_start_indices.is_empty() {
            new_mol_start_indices.push(0); // Mol 0 is solute
            for &idx in &self.mol_start_indices[1..] {
                new_mol_start_indices.push((idx as isize + diff) as usize);
            }
        }
        new_state.mol_start_indices = new_mol_start_indices;

        // --- Wish 7: Re-neutralize based on mutant net charge ---
        let q_scaled_sum: f32 = new_state.atoms.iter().map(|a| a.partial_charge).sum();
        let net_q_e = q_scaled_sum / CHARGE_UNIT_SCALER;
        let diff_q = net_q_e.round() as i32;

        if diff_q != 0 {
            let n_ions = diff_q.abs() as usize;
            if n_ions > 0 && !new_state.water.is_empty() {
                let (ff_type, elem, mass, q_scaled, sigma, eps): (&str, Element, f32, f32, f32, f32) =
                    if diff_q > 0 {
                        ("Cl-", Element::Chlorine, 35.45, -CHARGE_UNIT_SCALER, 4.478, 0.0073)
                    } else {
                        ("Na+", Element::Sodium, 22.99, CHARGE_UNIT_SCALER, 2.439, 0.1065)
                    };

                let stride = (new_state.water.len() / n_ions).max(1);
                let w_indices: Vec<usize> = (0..n_ions)
                    .map(|i| (i * stride).min(new_state.water.len() - 1))
                    .collect();

                for &w_idx in &w_indices {
                    insert_ion(&mut new_state, w_idx, ff_type, elem, mass, q_scaled, sigma, eps);
                }
                
                remove_waters(&mut new_state, w_indices);
                
                eprintln!(
                    "[solvent_reuse] Re-neutralized mutant net charge ({:+.3}e) by adding {} {} ion(s).",
                    net_q_e, n_ions, ff_type
                );
            }
        }

        // Populate other state parameters
        new_state.potential_energy_between_mols = vec![0.0; new_state.mol_start_indices.len().pow(2)];
        new_state.thermo_dof = new_state.dof_for_thermo();
        new_state.water_pme_sites_forces = vec![[lin_alg::f64::Vec3::new_zero(); 3]; new_state.water.len()];
        new_state.lj_tables = LjTables::new(&new_state.atoms);
        new_state.neighbors_nb = NeighborsNb::new(new_state.cfg.neighbor_skin, new_state.cfg.coulomb_cutoff);

        new_state.setup_nonbonded_exclusion_scale_flags();
        new_state.build_all_neighbors(dev);
        new_state.regen_pme(dev);

        new_state
    }
}
